### ISSUE TITLE
Optimized GPS & PPS config for u-blox NEO-M8N

### ISSUE THREAD

**Issue by geoffreyheller** [beta-tester/RPi-GPS-PPS-StratumOne#12]
Thanks for providing this great script for setting up the RPi Stratum One time server!

In addition to your script, I thought you might want to add some documentation for how to optimally set up the common u-blox NEO-M8N as a time source.

The following are the notes I used to configure my own M8N.  I was hoping to share this and potentially get some feedback / questions.   Once the config is agreed we could make an automated configuration script to set up the GPS devices themselves.

The following instructions are for u-center v21.09 and the NEO-M8N:

The following assumes that for configuration purposes you are connecting your PC to the M8N using a USB cable, and that your Raspberry Pi's ttyAMA0 UART is connected directly to UART1 on your M8N.

**FIRST RESET TO FACTORY DEFAULTS**
Tools > Firmware Update Utility
Check "Program FIS only"
FIS file: C:\Program Files (x86)\u-blox\u-center_v21.09\flash.xml
Check "Use chip erase"
GO

-or-

UBX > CFG > CFG
Reset to defaults
Send

**CONFIGURATION**
View > Configuration View

UBX > CFG > PRT
Target: 1 - UART1
Protocol out: 1 - NMEA
Change Baudrate to 115200
Send

UBX > CFG > CFG
Save current configuration
Send

NOTE:  U-center won't show a baud change since we are connected with USB and not UART1

UBX > CFG > GNSS
Enable GPS only (32 channels)
Send

UBX > CFG > SBAS
Subsystem: Disabled
Send

UBX > CFG > NAV5
Dynamic Model: 2 - Stationary
Send

UBX > CFG > TP5
Check Active
Pulse Period: 1000000
Check Align to TOW=0
Set: 0-UTC Time
Check Rising Edge on TOS
Send

UBX > CFG > PMS
Setup ID: 0-Full Power
Check: Save configuration
Send

UBX > CFG > RATE
Time Source: 0 - UTC Time
Send

UBX > CFG > MSG
Uncheck all boxes for:
F0-01 NMEA GxGGL
F0-02 NMEA GxGSA
F0-03 NMEA GxGSV
F0-04 NMEA GxRMC
F0-05 NMEA GxVTG

Check all boxes for:
F0-00 NMEA GxGGA
F0-08 NMEA GxZDA

(Summary: Keep only the GPGGA and GPZDA messages)

UBX > CFG > CFG
Save current configuration
Send

**Comment by geoffreyheller** [comment]
Update: I'm going to see if I can get the same settings using ubxtool

**Comment by beta-tester** [comment]
thanks,

but i do not plan to add documentations for a specific device (i not own).
i think the [u-blox documentation 'u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf'](https://content.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf) is good enough.

i will keep you feedback open for a while
