### ISSUE TITLE
suggestion: fs mgmt

### ISSUE THREAD

**Issue by EwaldvanGeffen** [beta-tester/RPi-GPS-PPS-StratumOne#18]
I sort of consider this myself an appliance, you might as well create dd images and distribute those almost. So I'm not entirely sure if this falls under the scope of this project but this is what I did on raspbian buster to tame my SD cards/disk writes.

```
root@acerola:~# grep -v ^# /etc/systemd/journald.conf

[Journal]
Storage=volatile
SystemMaxUse=64M
```
removing rsyslog/legacy facilities and disabling chrony statistical output will get your disk-write to nearly 0, 0.1w/s depending on your drive size/fs. I still need to setup statistics monitoring so I'm not certain how important that latest part is but we could put it in a RAM drive of some sort to make it more persistent/less write heavy

**Comment by beta-tester** [comment]
no, this will not happen. i will not distribute an image that is ready to flash.
