### ISSUE TITLE
Compatibility with Raspberry Pi 5?

### ISSUE THREAD

**Issue by AlexLandherr** [beta-tester/RPi-GPS-PPS-StratumOne#19]
Would it be possible to make this compatible with Raspberry Pi 5?

**Comment by beta-tester** [comment]
i don't have a RPi 5 to test.
what is not working ?

i don't see a package the script installs, that would not work on RasPi OS Bookworm.

**Comment by AlexLandherr** [comment]
I couldn't determine that for myself. I do have a Pi5B 4GB available and could try it possibly on Saturday this week.

**Comment by AlexLandherr** [comment]
> i don't have a RPi 5 to test.
> 
> what is not working ?
> 
> 
> 
> i don't see a package the script installs, that would not work on RasPi OS Bookworm.

I tested it just now with a NEO-M8T HAT and it works just fine. Also set a cronjob to write the system time to the built-in RTC daily at midnight.

**Comment by beta-tester** [comment]
thank you for the test
