### ISSUE TITLE
is it possible to access NMEA data using a Python program or a shell script?

### ISSUE THREAD

**Issue by BeamPower** [beta-tester/RPi-GPS-PPS-StratumOne#2]
After running your script, this is the closest I've ever been to getting my Adafruit GPS HAT to work on my Raspberry Pi Model 2 running Raspbian Stretch Lite.
I have been trying for weeks to get a system to adjust the time only from GPS and not use any Internet-based sources. This setup has to run with no Internet connectivity.
I have tried your test commands. I'm getting good sync, I think.

When I run chronyc sources, I get the following results:
210 Number of sources = 4
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
#* PPS                           0   3   377     9   +131ns[ +557ns] +/-  252ns
#- PPSx                          0   3   377     9   +128ns[ +128ns] +/-  249ns
#- PPSy                          0   3   377     9   +131ns[ +131ns] +/-  252ns
#- NMEA                          0   3   377     9    +49ms[  +49ms] +/-  109ms

Question 1: Why isn't NMEA showing a *?

When I run chronyc tracking, I get the following results:
Reference ID    : 50505300 (PPS)
Stratum         : 1
Ref time (UTC)  : Fri Feb 23 02:54:14 2018
System time     : 0.000000000 seconds fast of NTP time
Last offset     : -0.000001798 seconds
RMS offset      : 0.000000652 seconds
Frequency       : 3.760 ppm fast
Residual freq   : -0.027 ppm
Skew            : 0.135 ppm
Root delay      : 0.000000 seconds
Root dispersion : 0.000022 seconds
Update interval : 16.0 seconds
Leap status     : Normal

cgps -s works.
gpsmon works.

Question 2:
Is it possible to get access to NMEA messages on /dev/ttyAMA0 from a Python program?
If I run cat /dev/ttyAMA0, I get cat: /dev/ttyAMA0: Device or resource busy
If I run sudo cat /dev/ttyAMA0, I get nothing. It just bumps back to the prompt.

**Comment by beta-tester** [comment]
Q1: Why isn't NMEA showing a *?
A1: * indicates the source to which chronyd is currently synchronised.
the NMEA will be used in case all other sources are broken - e.g. when the GPS has no fix for PPS and is running on internal clock until it got fix again.
see `man chronyc` in der **Time sources**.
```
   Time sources
       sources [-v]
           This command displays information about the current time sources that chronyd is accessing.

           The optional argument -v can be specified, meaning verbose. In this case, extra caption lines are shown as a reminder of the meanings of the columns.

               210 Number of sources = 3
               MS Name/IP address         Stratum Poll Reach LastRx Last sample
               ===============================================================================
               #* GPS0                          0   4   377    11   -479ns[ -621ns] +/-  134ns
               ^? foo.example.net               2   6   377    23   -923us[ -924us] +/-   43ms
               ^+ bar.example.net               1   6   377    21  -2629us[-2619us] +/-   86ms

           The columns are as follows:

           M
               This indicates the mode of the source. ^ means a server, = means a peer and # indicates a locally connected reference clock.

           S
               This column indicates the state of the source.

               ·   * indicates the source to which chronyd is currently synchronised.

               ·   + indicates acceptable sources which are combined with the selected source.

               ·   - indicates acceptable sources which are excluded by the combining algorithm.

               ·   ? indicates sources to which connectivity has been lost or whose packets do not pass all tests. It is also shown at start-up, until at least 3 samples have been
                   gathered from it.

               ·   x indicates a clock which chronyd thinks is a falseticker (i.e. its time is inconsistent with a majority of other sources).

               ·   ~ indicates a source whose time appears to have too much variability.
```

Q2: Is it possible to get access to NMEA messages on /dev/ttyAMA0 from a Python program?
A2: not directly by accessing the /dev/ttyAMA0.
but you can use a gpsd client like cgps is doing, but only for python.
e.g. https://pypi.python.org/pypi/gpsd-py3/0.2.0
https://github.com/MartijnBraam/gpsd-py3

**Comment by BeamPower** [comment]
So these are good results?

As long as PPS is solid, I should be happy?

 

~ $ chronyc sources
210 Number of sources = 4
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
#* PPS                           0   3   377     8   +201ns[ +306ns] +/-  177ns
#- PPSx                          0   3   377     8   +201ns[ +201ns] +/-  176ns
#- PPSy                          0   3   377    11    +23ns[ +123ns] +/-  197ns
#- NMEA                          0   3   377     9  +2617us[+2617us] +/-  108ms

 


~ $ sudo ppstest /dev/pps0
trying PPS source "/dev/pps0"
found PPS source "/dev/pps0"
ok, found 1 source(s), now start fetching data...
source 0 - assert 1519950344.000001047, sequence: 278283 - clear  0.000000000, sequence: 0
source 0 - assert 1519950345.000000025, sequence: 278284 - clear  0.000000000, sequence: 0
source 0 - assert 1519950345.999999208, sequence: 278285 - clear  0.000000000, sequence: 0

 

~ $ sudo ntpshmmon
ntpshmmon version 1
#      Name   Seen@                Clock                Real               L Prec
sample NTP0 1519950411.611632642 1519950411.553805031 1519950411.000000000 0  -1
sample NTP2 1519950412.000728072 1519950412.000001511 1519950412.000000000 0 -20
sample NTP0 1519950412.112254875 1519950411.553805031 1519950411.000000000 0  -1
sample NTP0 1519950412.612974972 1519950412.505427787 1519950412.000000000 0  -1
sample NTP2 1519950413.001173635 1519950413.000000826 1519950413.000000000 0 -20

 

Thanks!


 

Sent: Saturday, February 24, 2018 at 8:13 AM

**Comment by BeamPower** [comment]
After having so much difficulty trying to access the dev/ttyAMA0 port using the serial.Serial object code in Python, my colleague showed me this little gem of a script.

Works great!

Later, I added some code to write the data to a file, but you get the idea.

 

 


import gps

# Listen on port 2947 (gpsd) of localhost
session = gps.gps("localhost", "2947")
session.stream(gps.WATCH_ENABLE | gps.WATCH_NEWSTYLE)

while True:
    try:
        report = session.next()
        # Wait for 'TPV' report and display the current time
        # To see all report data, uncomment the line below
        #print report
        if report['class'] == 'TPV':
            if hasattr(report, 'time'):
                print report.time, report.lat, report.lon
                                break
    except KeyError:
        pass
    except KeyboardInterrupt:
        quit();
    except StopIteration:
        session = None
        print "GPSD has terminated"

 

 


 

Sent: Saturday, February 24, 2018 at 8:13 AM

**Comment by BeamPower** [comment]
Cool!

I'll give it a try.

Always more than one way to skin a cat.

 

 

Sent: Sunday, February 25, 2018 at 2:18 AM

**Comment by beta-tester** [comment]
> So these are good results?
As long as PPS is solid, I should be happy?

yes, your results looks good. every thing is working as expected.
if you have at least one * in the list and no ?, x or ~, then you can be happy.
chrony decides which of the sources will be taken to get the best result.

in case you need the raw NMEA data instead of "converted" position data, then you should take a closer look to the gpsd documentation.
www.catb.org/gpsd/client-howto.html

open a TCP connection to the gpsd server as port 2947 e.g. using telnet
and send "?WATCH={"enable":true,"nmea":true};" and gpsd will send you data in NMEA format instead of json format. but i dont know if those NMEA data are the original ones from the GPS device or if those NMEA data you get are "synthesized" data like:
NMEA data from GPS device to gpsd internal data, then from gpsd internal data synthesized back to NMEA as requested from client.
