### ISSUE TITLE
Some added context for installs

### ISSUE THREAD

**Issue by CvW** [beta-tester/RPi-GPS-PPS-StratumOne#22]
Good afternoon, 
Not everyone may be as familiar with setting up a Rasberry pi, so I wonder if you would consider adding some guidance to your introduction. 

Specifically, after setup, running 
`sudo apt update` followed by `sudo apt update`  
then `sudo apt install git` to install git, which will make downloading your repository simple. 
Lastly, `git clone https://github.com/beta-tester/RPi-GPS-PPS-StratumOne.git`

**Comment by beta-tester** [comment]
thanks, i added a step 0.

see: https://github.com/beta-tester/RPi-GPS-PPS-StratumOne/commit/db458709b41615a35002d0bfaeb2c915c00e4bf4
