### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by westridaz** [beta-tester/RPi-GPS-PPS-StratumOne#23]
Im trying to work with the offset but i have no clue wat to fill in for offset.

If tried the gnuplot but im not understanding how it works.

All settings are still on default

![{DCD550CD-A43F-488C-B320-386272E02AD8}](https://github.com/user-attachments/assets/fcb88eb5-b5fc-48e3-9aff-ba078725bb41)

Running Raspberry Pi 4 with Uputronics GPS HAT / latest Raspberry image

**Comment by beta-tester** [comment]
- wondering if this are the settings from my files - non of the names fit to my files.
- how long was the GPS receiver running with a FIX - active PPS signal?
- what do you get from `chronyc -m tracking sources` ?

**Comment by westridaz** [comment]
Not sure wat happend here,  but i just rerun the installer

<img width="576" alt="Scherm­afbeelding 2024-11-06 om 08 44 33" src="https://github.com/user-attachments/assets/773cd359-cbcd-40e2-86cf-d597a6cb6f4e">

But after changing 20-ntp-servers.conf and finishing with sudo systemctl stop --now gpsd.{service,socket} &&          sudo systemctl stop chrony &&          sudo systemctl start chrony &&          sudo systemctl start gpsd
i dont get pps or gps

<img width="568" alt="Scherm­afbeelding 2024-11-06 om 08 50 24" src="https://github.com/user-attachments/assets/a5eaf941-7fe6-4bbd-8b1d-a97c5a9b7411">

If let it run for atleast 30minuts atleast but with a reboot of the pi i got pps & gps back again

<img width="663" alt="Scherm­afbeelding 2024-11-06 om 08 58 35" src="https://github.com/user-attachments/assets/f362fac7-726c-455e-b509-a3fe77f9e5bb">

**Comment by westridaz** [comment]
Got it figured why its not working at all.

Faulty sd card

New sd card with all defaults settings is working

Thanks for the help anyway
