### ISSUE TITLE
gpsd startup conflicts

### ISSUE THREAD

**Issue by NHMatt** [beta-tester/RPi-GPS-PPS-StratumOne#3]
Could gpsd.socket be interfering with gpsd, or could something else be taking place?

Using Raspbian Stretch Lite 2018-03-13 on a RPi 3, syslog shows:

Apr  1 10:55:36 tocktick gpsd[657]: gpsd:ERROR: /dev/ttyAMA0 already opened by another process
Apr  1 10:55:36 tocktick gpsd[657]: gpsd:ERROR: initial GPS device /dev/ttyAMA0 open failed
Apr  1 10:56:23 tocktick gpsd[657]: gpsd:ERROR: device open of /dev/ttyAMA0 failed: Device or resource busy - retrying read-only
Apr  1 10:56:23 tocktick gpsd[657]: gpsd:ERROR: read-only device open of /dev/ttyAMA0 failed: Device or resource busy
Apr  1 10:56:23 tocktick gpsd[657]: gpsd:ERROR: /dev/ttyAMA0: device activation failed.
Apr  1 10:56:23 tocktick gpsd[657]: gpsd:ERROR: /dev/ttyAMA0: activation failed, freeing device

**Comment by beta-tester** [comment]
did you just installed **_Raspbian Stretch Lite 2018-03-13_** and run the script,
or did you have something else installed already or modified the script?
i don't have a RPi3 available at the moment to try out, but i mean to remember, that the build-in bluetooth interface of the RPi3 is using a serial port. maybe you can run raspi-config first and disable all bluetooth stuff.

**Comment by NHMatt** [comment]
It was a freshly-installed copy of Stretch Lite.

I just disabled bluetooth (via adding the line "dtoverlay=pi3-disable-bt" to /boot/config.txt) 

All seems to be working perfectly now.  Thanks!

**Comment by beta-tester** [comment]
thank you for the info how you got it work.

**Comment by PumaSnipes** [comment]
givs any body they have the same problem?


Dec 23 09:48:57 raspberrypi gpsd[372]: gpsd:ERROR: SER: device open of /dev/ttyS0 failed: No such file or directory - retrying read-only
Dec 23 09:48:57 raspberrypi gpsd[372]: gpsd:ERROR: SER: read-only device open of /dev/ttyS0 failed: No such file or directory
Dec 23 09:48:57 raspberrypi gpsd[372]: gpsd:ERROR: initial GPS device /dev/ttyS0 open failed

**Comment by ComputerSmiths** [comment]
Did it ever work or are you setting this up for the first time?

If it used to work I’m guessing hardware failure, if initial setup probably need to find the actual serial port. 

William Smith
ComputerSmiths Consulting, Inc. 
***@***.***

**Comment by beta-tester** [comment]
can you try `/dev/ttyAMA0` instead of  `/dev/ttyS0`. as i can remember,
in gpad there is something hard coded only for Raspberry pi and only for `/dev/ttyAMA0`.

and be sure **blutetooth** and **serial console** is **disabled** but **serial port** is **enabled**.
