### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by sjwissow** [beta-tester/RPi-GPS-PPS-StratumOne#6]
Thank you for sharing this project. Would you consider [adding](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) a [license](https://choosealicense.com)? I ask because I would like to adapt your work to support experiments I will run as part of my masters thesis.

**Comment by beta-tester** [comment]
what kind of common license would fit best here?
it's a common script that anyone could have written like this.
there is nothing special in this script?

**Comment by sjwissow** [comment]
Thank you for you reply. That is a good question. I am not an expert with licenses, but I think without a license your script is technically copyrighted solely to you, and while the GitHub terms allow forking it on the GitHub platform, I'm not sure I would technically be allowed to use the script in my work outside of the GitHub platform.

If you want to release the script to the public domain, it looks like the [Unlicense](https://choosealicense.com/licenses/unlicense/) might provide the greatest amount of flexibility for others to use your script; however, I think you would also be giving up your rights as the copyright holder. If this is not something you want to do, then there may be a different license that better fits your goals and priorities, or you might prefer not to license it at all, and to retain copyright.

**Comment by beta-tester** [comment]
i added a licence.
I hope the license i choosed is in your senses

**Comment by sjwissow** [comment]
Thank you!
